# Generated by Django 5.2.1 on 2025-05-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParsedPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2048)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("h1_count", models.PositiveIntegerField()),
                ("h2_count", models.PositiveIntegerField()),
                ("h3_count", models.PositiveIntegerField()),
                ("links", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
